[build]
  publish = "/"
  command = "echo 'No build command needed'"

[[redirects]]
  from = "/api/results"
  to = "https://satta-king-fast.com/"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/api/chart"
  to = "https://satta-king-fast.com/"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# Redirects for SPAs
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200